### ISSUE TITLE
connect command added 2 duplicate projects to the dependencies.yml

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-meshify#127]
![Screenshot 2023-08-18 at 2 31 02 PM](https://github.com/dbt-labs/dbt-meshify/assets/53586774/3111cb3d-1f60-4be9-97ba-e8103d234b40)
 
<img width="885" alt="Screenshot 2023-08-18 at 2 33 10 PM" src="https://github.com/dbt-labs/dbt-meshify/assets/53586774/9fac3a6c-996b-453b-8e5f-00f64b5b23dc">

**Comment by nicholasyager** [comment]
This is interesting on two counts.
1. We shouldn't be triggering two project dependency addition changes in the same run. This tells me that the dependency code might need to be updated to trigger once.
2. I _think_ the `projects` list in `dependencies.yml` should be parsed as a `NamedList`. If it is, then there may be a defect in how `safe_update` is handling string indexing of `NamedList` elements. If it's _not_ being deserialized into a `NamedList`, then we may need to update the parser to make this explicit.

**Comment by nicholasyager** [comment]
A quick check would suggest that both of these are incorrect :lolsob: We can end up with multiple dependency file changes, which is not an inherently bad thing. The trickier part is that we are currently performing a `FileChange` to create a dependency.yml file, but this is really more akin to a `ResourceChange`. This is an important distinction, since `ResourceChange`s allow us to ignore current file contents and add/update wherever necessary. 

With this in mind, my official recommendation is to update the `update_demendencies_yml` method to instead return a `ResourceChange` that simply adds a project entry if it doesn't already exist.

**Comment by dave-connors-3** [comment]
completed by #132
